// <auto-generated />
namespace Rinku.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class ObjetoMovimiento : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ObjetoMovimiento));
        
        string IMigrationMetadata.Id
        {
            get { return "201808051933497_Objeto-Movimiento"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
